import React from 'react'



export const metadata = {
  title: "info Page",
  description: "Generated by create next app",
};


function page() {
  return (
    <div>
      <h1>Hello React Info!</h1>
    </div>
  )
}

export default page
